slaPS1=" 🐢  💨  \W "
export PS1

# ddexport
# PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '

alias dpr='git checkout develop && git pull --rebase origin develop'

alias python='python2.7'
export NVM_DIR="/Users/ACKeepingitCoo/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
. ~/.bashrc
. ~/.bashrc

export PATH=/usr/bin:$PATH
